import type { EnterpriseKnowledgeItem } from '@role-clarifier/contracts'

const updatedAt = '2026-08-18T00:00:00.000Z'

export const demoEnterpriseKnowledge: EnterpriseKnowledgeItem[] = [
  {
    id: 'EK-ORG-PRODUCT-001',
    tenant_id: 'tenant-demo',
    category: 'ORGANIZATION',
    title: '企业服务产品部职责',
    content: '来源：模拟公司组织职责说明。企业服务产品部负责把客户项目中反复出现的需求沉淀为标准产品能力，建立产品边界、路线图和跨客户验证机制；与销售、交付、研发共同判断需求优先级，但不承担单一客户项目的定制交付管理。',
    summary: '企业服务产品部面向标准产品经营，负责共性需求识别、产品边界、路线图和跨客户验证。',
    department: '企业服务产品部',
    job_family: '产品',
    tags: ['企业服务产品部', '组织职责', '产品边界', '跨客户验证', '岗位使命'],
    visible_to: 'ALL_ROLE_MEMBERS',
    source_ref: 'mock://organization/product-division',
    source_version: '2026.08',
    status: 'ACTIVE',
    valid_from: '2026-08-01T00:00:00.000Z',
    valid_to: null,
    updated_at: updatedAt,
  },
  {
    id: 'EK-JOB-PRODUCT-001',
    tenant_id: 'tenant-demo',
    category: 'JOB_FAMILY',
    title: '产品岗位族能力框架',
    content: '来源：模拟公司产品岗位族能力框架。产品岗位从业务洞察、问题定义、方案判断、数据验证和跨团队推动五个维度建立能力要求。岗位画像应把能力落到真实工作场景、可观察行为和结果证据，避免只写抽象素质词。',
    summary: '产品岗位族以业务洞察、问题定义、方案判断、数据验证和跨团队推动为核心能力维度。',
    department: '企业服务产品部',
    job_family: '产品',
    tags: ['产品', '岗位族', '能力框架', '业务洞察', '跨团队推动', '评估维度'],
    visible_to: 'ALL_ROLE_MEMBERS',
    source_ref: 'mock://job-family/product',
    source_version: '2026.08',
    status: 'ACTIVE',
    valid_from: '2026-08-01T00:00:00.000Z',
    valid_to: null,
    updated_at: updatedAt,
  },
  {
    id: 'EK-LEVEL-34-001',
    tenant_id: 'tenant-demo',
    category: 'LEVEL_FRAMEWORK',
    title: '3-2 至 4-1 职级要求',
    content: '来源：模拟公司产品序列职级标准。3-2 需要独立负责一个复杂产品方向，能够定义目标、协调多角色并用数据复盘；4-1 还需要处理跨部门取舍、沉淀可复用机制并对中长期业务结果负责。澄清时应结合岗位授权范围确定实际职级，不以工作年限直接替代能力证据。',
    summary: '3-2 强调独立负责复杂方向，4-1 增加跨部门取舍、机制沉淀和中长期结果责任。',
    department: '企业服务产品部',
    job_family: '产品',
    tags: ['职级', '3-2', '4-1', '授权范围', '结果责任', '能力证据'],
    visible_to: 'ALL_ROLE_MEMBERS',
    source_ref: 'mock://level/product-3-2-4-1',
    source_version: '2026.08',
    status: 'ACTIVE',
    valid_from: '2026-08-01T00:00:00.000Z',
    valid_to: null,
    updated_at: updatedAt,
  },
  {
    id: 'EK-JD-PM-001',
    tenant_id: 'tenant-demo',
    category: 'HISTORICAL_JD',
    title: '企业产品经理历史岗位说明',
    content: '来源：模拟公司已归档岗位说明。该岗位面向企业客户的共性场景，负责识别可规模化的问题、规划标准产品路线、协调研发与交付，并通过多客户验证衡量产品价值。对外岗位说明应突出真实使命、关键工作和可验证要求，不披露内部预算与审批信息。',
    summary: '历史岗位说明强调共性场景识别、标准产品路线、跨团队交付和多客户价值验证。',
    department: '企业服务产品部',
    job_family: '产品',
    tags: ['历史JD', '企业产品经理', '岗位职责', '标准产品', '公开JD'],
    visible_to: 'ALL_ROLE_MEMBERS',
    source_ref: 'mock://historical-jd/enterprise-pm',
    source_version: '2026.08',
    status: 'ACTIVE',
    valid_from: '2026-08-01T00:00:00.000Z',
    valid_to: null,
    updated_at: updatedAt,
  },
  {
    id: 'EK-ROLE-PM-001',
    tenant_id: 'tenant-demo',
    category: 'ROLE_PROFILE_CASE',
    title: '企业产品经理成功画像案例',
    content: '来源：模拟公司岗位画像案例库。成功案例把招聘原因写成业务变化与组织缺口，把岗位使命写成需要承担的结果，并用九十天路线图、跨客户验证和复用率等结果描述成功标准；能力要求逐项映射工作场景、强证据和面试方法。',
    summary: '成功画像案例用业务变化、组织缺口、岗位使命、阶段结果和证据化能力要求形成完整判断链。',
    department: '企业服务产品部',
    job_family: '产品',
    tags: ['岗位画像', '成功标准', '招聘原因', '工作场景', '证据链', '企业产品经理'],
    visible_to: 'ALL_ROLE_MEMBERS',
    source_ref: 'mock://role-profile/enterprise-pm',
    source_version: '2026.08',
    status: 'ACTIVE',
    valid_from: '2026-08-01T00:00:00.000Z',
    valid_to: null,
    updated_at: updatedAt,
  },
  {
    id: 'EK-RECRUIT-POLICY-001',
    tenant_id: 'tenant-demo',
    category: 'RECRUITING_POLICY',
    title: '招聘审批与筛选协作规范',
    content: '来源：模拟公司招聘管理规范。编制审批完成后由系统向用人经理创建岗位澄清任务；用人经理确认岗位事实和画像，招聘伙伴在站内查看进度，并依据已确认画像筛选简历。岗位画像、评估方案和公开岗位说明完成确认后才进入正式招聘执行。',
    summary: '审批后由用人经理完成画像澄清，招聘伙伴跟踪进度并依据确认结果筛选，正式产物确认后启动招聘。',
    department: null,
    job_family: null,
    tags: ['HC审批', '招聘协作', '用人经理', 'HR', '筛选标准', '任务进度'],
    visible_to: 'HR_ONLY',
    source_ref: 'mock://recruiting-policy/approved-role',
    source_version: '2026.08',
    status: 'ACTIVE',
    valid_from: '2026-08-01T00:00:00.000Z',
    valid_to: null,
    updated_at: updatedAt,
  },
  {
    id: 'EK-INTERVIEW-PM-001',
    tenant_id: 'tenant-demo',
    category: 'INTERVIEW_STANDARD',
    title: '产品岗位结构化面试标准',
    content: '来源：模拟公司产品岗位面试规范。面试维度必须来自已确认岗位画像，围绕业务判断、问题拆解、方案取舍、数据验证和协作推动设置问题；每个维度要写明可观察证据、评分锚点和责任面试官，并在面试后按同一标准校准。',
    summary: '结构化面试从岗位画像生成维度，为每项能力定义问题、证据、评分锚点和面试责任人。',
    department: '企业服务产品部',
    job_family: '产品',
    tags: ['结构化面试', '面试标准', '评分锚点', '能力证据', '岗位画像', '校准'],
    visible_to: 'ALL_ROLE_MEMBERS',
    source_ref: 'mock://interview-standard/product',
    source_version: '2026.08',
    status: 'ACTIVE',
    valid_from: '2026-08-01T00:00:00.000Z',
    valid_to: null,
    updated_at: updatedAt,
  },
]
