export const roleSessionsSeed = [
  {
    id: 'role-enterprise-pm',
    name: '企业产品经理',
    team: '企业服务产品部',
    stage: '需求澄清中',
    stageTone: 'active',
    meta: '3 项待确认',
    version: '草稿 v0.4',
    updatedAt: '刚刚',
    unread: 2,
  },
  {
    id: 'role-commercial-pm',
    name: '商业化产品经理',
    team: '商业产品部',
    stage: '简历校准中',
    stageTone: 'calibrating',
    meta: '已导入 15 份',
    version: '画像 V0',
    updatedAt: '昨天',
  },
  {
    id: 'role-data-pm',
    name: '数据产品经理',
    team: '数据平台部',
    stage: '画像已确认',
    stageTone: 'confirmed',
    meta: 'V1 已确认',
    version: '画像 V1',
    updatedAt: '8 月 12 日',
  },
];

export const contextSources = [
  { id: 'org', label: '组织背景', detail: '组织系统 · 已同步', icon: 'org', evidenceId: 'E-02' },
  { id: 'jd', label: '旧 JD', detail: '招聘系统 · 2024-03', icon: 'doc', evidenceId: 'E-03' },
  { id: 'cases', label: '历史录用案例', detail: '人才库 · 3 人', icon: 'people', evidenceId: 'E-05' },
  { id: 'market', label: '人才供给', detail: '人才库 · 最近 90 天', icon: 'database', evidenceId: 'E-06' },
];

export const evidenceById = {
  'E-01': {
    id: 'E-01',
    type: '业务需求',
    title: '本次招聘原因',
    source: '用人经理 / 会话输入',
    time: '今天 10:27',
    quote: '今年要把企业服务从跟着项目走，转成有明确标准产品路线。现在每个客户都要重新做一遍，产品和研发资源被不断拉散。',
    supports: ['招聘背景', '不招聘的影响'],
    status: '已确认',
  },
  'E-02': {
    id: 'E-02',
    type: '系统资料',
    title: '组织目标与协作关系',
    source: '组织系统 / 企业服务产品部',
    time: '今天 10:29',
    quote: '该岗位汇报产品负责人，核心协作对象包括销售、交付、研发与解决方案团队。团队今年的重点是从定制项目交付转向标准产品。',
    supports: ['岗位使命', '协作关系', '权责边界'],
    status: '已同步',
  },
  'E-03': {
    id: 'E-03',
    type: '历史资料',
    title: '旧 JD · 工作重点',
    source: '招聘系统 / 2024 年版本',
    time: '2024-03-18',
    quote: '负责重点客户项目需求承接、解决方案设计、项目交付与验收。',
    supports: ['关键任务', '工作边界'],
    status: '与当前方向冲突',
    conflict: '旧 JD 偏客户项目交付；本次业务需求强调标准化、平台化和跨项目复用。',
  },
  'E-04': {
    id: 'E-04',
    type: '业务数据',
    title: '项目重复建设现状',
    source: '项目复盘 / 最近 12 个月',
    time: '今天 10:30',
    quote: '重点客户项目中存在大量相似需求，但缺少统一分类、产品边界和复用率指标，研发排期仍以单项目紧急程度驱动。',
    supports: ['90 天成功结果', '关键工作场景', '衡量指标'],
    status: '事实已确认，基线待补数',
  },
  'E-05': {
    id: 'E-05',
    type: '人才库资料',
    title: '历史录用与高绩效案例',
    source: '人才库 / 同类岗位',
    time: '近 24 个月',
    quote: '3 名历史录用者均有复杂 B 端项目经历，其中 2 人具有从交付型产品向平台产品转型的完整案例。高绩效差异主要来自问题抽象和跨团队取舍，而不是行业年限。',
    supports: ['核心能力', '有效候选人证据', '面试验证方式'],
    status: '可参考，不直接作为硬门槛',
  },
  'E-06': {
    id: 'E-06',
    type: '人才供给',
    title: '外部人才供给快照',
    source: '人才库 / 最近 90 天',
    time: '今天 10:30',
    quote: '同时满足“3 年同行业”与“平台产品落地”的可触达人才仅占初步样本的 13%，预计招聘周期将增加 3—4 周。',
    supports: ['经验门槛', '招聘策略'],
    status: '待用人经理权衡',
  },
  'E-07': {
    id: 'E-07',
    type: '对话证据',
    title: '90 天成功结果',
    source: '用人经理 / 当前对话',
    time: '今天 10:36',
    quote: '第一优先是完成现状诊断，把过去项目里的共性机会找出来，形成产品路线并让几个关键团队认可。',
    supports: ['90 天成功结果', '成功评分卡'],
    status: '方向已确认，指标待确认',
  },
  'E-08': {
    id: 'E-08',
    type: '对话证据',
    title: '岗位使命',
    source: '用人经理 / 当前对话',
    time: '今天 10:32',
    quote: '当前最大的业务问题是，每个客户项目都要重新做一遍，方案很难复用。这个岗位要真正把共性东西沉淀成产品。',
    supports: ['岗位使命', '业务问题'],
    status: '高置信度',
  },
  'E-09': {
    id: 'E-09',
    type: '招聘约束',
    title: '编制与招聘约束',
    source: '招聘需求单 / HR 补充',
    time: '今天 10:31',
    quote: '新增正式编制 1 人，职级建议 3-2 至 4-1，北京或上海，期望 8 周内到岗。薪酬预算已通过初审。',
    supports: ['编制', '职级', '地点', '招聘周期'],
    status: 'HR 已确认',
  },
};

export const roleProfile = {
  meta: {
    title: '企业产品经理',
    team: '企业服务产品部',
    reportsTo: '产品负责人',
    headcount: '新增编制 1 人',
    level: '3-2 至 4-1',
    location: '北京 / 上海',
    stage: '需求澄清中',
    version: '草稿 v0.4',
    completeness: 76,
    confirmed: 18,
    pending: 3,
    conflicts: 1,
    evidenceCount: 9,
  },
  recruitment: {
    reason: '企业服务业务正在从单客户定制交付转向标准产品经营，但当前缺少对跨项目共性需求和产品路线负责的人。',
    businessChange: '研发排期由单项目紧急需求驱动，多个客户的相似能力重复建设，产品边界与复用价值没有被持续管理。',
    noHireImpact: '标准化路线将继续被项目节奏打断，重复研发和交付成本难以下降，核心客户经验无法沉淀为规模化产品能力。',
    mission: '将分散在客户交付中的共性需求转化为可规模复用的标准产品，并推动产品完成核心客户验证。',
    evidence: ['E-01', 'E-02', 'E-04', 'E-08'],
  },
  boundaries: {
    owns: [
      '跨项目需求洞察、产品边界和标准化路线',
      '核心能力的优先级、MVP 定义与验证指标',
      '销售、交付、研发之间的产品化取舍依据',
    ],
    notOwns: [
      '单个客户项目的进度管理和最终验收',
      '销售合同承诺与临时定制需求的直接交付',
    ],
    decisionRights: '可提出产品路线与需求取舍建议；是否具有最终优先级否决权仍需产品负责人确认。',
    resources: '与销售、解决方案、交付和研发协作；专属研发容量与数据支持尚待确认。',
    evidence: ['E-02', 'E-03'],
  },
  outcomes: [
    {
      id: 'O-01',
      horizon: '入职 90 天',
      title: '完成标准化机会诊断，并形成经关键团队评审的产品路线',
      definition: '复盘最近 12 个月不少于 20 个代表性项目，识别至少 3 个高价值共性机会，明确产品边界、价值假设和优先级。',
      measures: ['代表性项目覆盖', '共性机会质量', '路线评审通过', '关键角色共识'],
      status: '方向已确认 · 数字待确认',
      tone: 'pending',
      evidence: ['E-04', 'E-07'],
    },
    {
      id: 'O-02',
      horizon: '入职 6 个月',
      title: '推动首个标准能力完成 MVP 并进入核心客户验证',
      definition: '完成一个优先级最高的标准能力 MVP，至少进入 2 个核心客户试点，建立采用率、定制需求占比和交付周期基线。',
      measures: ['MVP 按关键范围上线', '2 个客户试点', '验证指标可观测', '复盘形成迭代决策'],
      status: 'Agent 草拟 · 待经理确认',
      tone: 'warning',
      evidence: ['E-01', 'E-04', 'E-08'],
    },
    {
      id: 'O-03',
      horizon: '入职 12 个月',
      title: '形成可规模复用的产品能力与持续经营机制',
      definition: '标准能力覆盖不少于 5 个活跃客户，目标场景复用率达到 60%，平均定制交付周期下降 30%；具体目标需结合当前基线确认。',
      measures: ['活跃客户覆盖', '场景复用率', '交付周期改善', '路线持续迭代'],
      status: '目标值待业务确认',
      tone: 'warning',
      evidence: ['E-01', 'E-04'],
    },
  ],
  scenarios: [
    {
      id: 'T-01',
      title: '跨项目业务诊断与共性抽象',
      frequency: '入职前 90 天高频，之后按季度复盘',
      trigger: '多个客户提出相似但表达不同的需求，团队无法判断应该定制还是产品化。',
      actions: '梳理业务目标、使用场景、差异和共性，建立需求分类与机会评估框架。',
      output: '项目需求图谱、共性机会清单、产品边界判断。',
      challenge: '避免被最大客户或最紧急项目绑架，同时保留高价值差异。',
      stakeholders: '销售、解决方案、交付、客户成功',
      outcomes: ['O-01'],
      evidence: ['E-04', 'E-08'],
    },
    {
      id: 'T-02',
      title: '产品路线与优先级决策',
      frequency: '月度规划与重大需求触发',
      trigger: '业务价值、客户承诺、研发成本和长期产品方向发生冲突。',
      actions: '建立统一决策依据，量化价值与成本，明确做、不做和延后，并推动关键角色承诺。',
      output: '产品路线图、需求决策记录、范围与里程碑。',
      challenge: '在缺乏完整数据时作出可解释、可回溯的取舍。',
      stakeholders: '产品负责人、研发负责人、销售负责人、交付负责人',
      outcomes: ['O-01', 'O-02'],
      evidence: ['E-02', 'E-03'],
    },
    {
      id: 'T-03',
      title: '标准能力定义与 MVP 推动',
      frequency: '每个产品化机会 1 个完整周期',
      trigger: '标准化机会进入路线，需要从客户方案转化为清晰的产品能力。',
      actions: '定义核心用户、场景边界、能力模型和 MVP，协调研发完成方案并控制范围。',
      output: '产品方案、MVP 范围、验收标准、上线计划。',
      challenge: '既满足首批客户验证，又避免把首个客户需求重新做成定制项目。',
      stakeholders: '研发、设计、解决方案、试点客户',
      outcomes: ['O-02'],
      evidence: ['E-03', 'E-05'],
    },
    {
      id: 'T-04',
      title: '核心客户试点与价值验证',
      frequency: 'MVP 上线前后持续 2—3 个月',
      trigger: '标准能力需要验证真实采用、业务价值和可复制性。',
      actions: '选择代表性客户，设计验证计划，跟踪采用和反馈，区分产品问题与实施问题。',
      output: '试点方案、验证数据、问题清单、是否扩大投入的决策。',
      challenge: '从单客户满意度转向对规模化价值的判断。',
      stakeholders: '核心客户、客户成功、交付、研发',
      outcomes: ['O-02', 'O-03'],
      evidence: ['E-04', 'E-05'],
    },
    {
      id: 'T-05',
      title: '产品复用与经营指标建设',
      frequency: '月度跟踪，季度复盘',
      trigger: '标准能力进入多个客户，需要判断复用效率和持续投入价值。',
      actions: '定义复用率、采用率、定制占比和交付周期指标，建立持续复盘机制。',
      output: '指标看板、经营复盘、下一阶段路线调整。',
      challenge: '补齐历史数据基线，并把指标真正用于产品决策。',
      stakeholders: '数据、研发、交付、业务负责人',
      outcomes: ['O-03'],
      evidence: ['E-04'],
    },
  ],
  requirements: [
    {
      id: 'C-01',
      priority: 'Must-have',
      title: '复杂 B 端问题抽象与产品化',
      level: '能够独立完成',
      why: '直接决定能否从差异化客户项目中识别可复用机会，支撑 O-01。',
      mapping: ['T-01', 'T-02'],
      strongEvidence: '曾覆盖多个客户或业务单元，能够说明如何识别共性、定义边界，并最终形成标准能力。',
      substitute: '没有本行业经验，但做过相似复杂度的企业产品或交付转产品经历。',
      risk: '只会汇总需求；以客户数量代替抽象过程；无法说明放弃了什么。',
      assessment: '案例面试 + 经历深挖',
      evidence: ['E-05', 'E-08'],
    },
    {
      id: 'C-02',
      priority: 'Must-have',
      title: '从机会判断到 MVP 验证的闭环能力',
      level: '至少主导过 1 次',
      why: '岗位不仅输出路线，还必须推动首个标准能力完成验证，支撑 O-02。',
      mapping: ['T-03', 'T-04'],
      strongEvidence: '能完整说明机会判断、MVP 取舍、上线验证、指标结果和后续迭代。',
      substitute: '在平台能力、行业解决方案或复杂内部产品中完成过相同闭环。',
      risk: '只有方案或上线经历，没有用户采用、业务结果和复盘。',
      assessment: '项目复盘面试',
      evidence: ['E-05'],
    },
    {
      id: 'C-03',
      priority: 'Must-have',
      title: '跨销售、交付与研发的决策推动',
      level: '能够在无直接汇报关系下推动',
      why: '标准化过程必然触碰客户承诺和短期收入，需要形成可解释的组织取舍。',
      mapping: ['T-02', 'T-03'],
      strongEvidence: '能够还原目标冲突、决策依据、关键角色承诺和最终结果，而不只是“沟通协调”。',
      substitute: '在矩阵组织或多业务线环境中推动过同类高冲突决策。',
      risk: '依赖上级拍板；回避冲突；无法说明自己改变了什么。',
      assessment: '行为面试 + 交叉追问',
      evidence: ['E-02', 'E-05'],
    },
    {
      id: 'C-04',
      priority: 'Must-have',
      title: '以指标验证产品价值',
      level: '能够定义并使用核心指标',
      why: '岗位需要证明标准能力是否真正被采用并改善交付效率，支撑 O-02、O-03。',
      mapping: ['T-04', 'T-05'],
      strongEvidence: '能说明指标定义、基线、数据限制以及指标如何改变产品决策。',
      substitute: '具备扎实的实验、运营分析或业务经营分析经验。',
      risk: '只报告上线数量、需求数量或客户满意度，没有价值指标。',
      assessment: '案例任务 + 数据追问',
      evidence: ['E-04'],
    },
    {
      id: 'C-05',
      priority: 'Preferred',
      title: '企业服务客户与交付链路理解',
      level: '能够快速进入复杂业务场景',
      why: '能够降低理解多角色决策链和实施约束的时间成本，但不是替代核心能力的硬门槛。',
      mapping: ['T-01', 'T-04'],
      strongEvidence: '接触过采购、决策、使用和交付角色分离的复杂 B 端场景。',
      substitute: '平台产品、产业互联网或复杂内部系统经历。',
      risk: '把单一行业术语熟悉度等同于产品能力。',
      assessment: '经历深挖',
      evidence: ['E-05', 'E-06'],
    },
    {
      id: 'C-06',
      priority: 'Preferred',
      title: '同行业经验',
      level: '加速项，不作为简历硬筛',
      why: '可能提高场景理解速度，但人才供给有限，历史案例也未证明行业年限直接决定绩效。',
      mapping: ['T-01'],
      strongEvidence: '不仅熟悉行业，还能提供从行业洞察到产品决策与结果的完整证据。',
      substitute: '相似客户复杂度、相似产品化转型或平台能力建设经历。',
      risk: '只有行业 tenure，没有复杂问题抽象或产品化结果。',
      assessment: '简历参考，不单独评分',
      evidence: ['E-05', 'E-06'],
    },
  ],
  scorecard: [
    {
      id: 'A-01',
      dimension: '复杂问题抽象与产品化',
      weight: 30,
      mapsTo: ['O-01', 'C-01'],
      method: '60 分钟案例面试',
      owner: '产品负责人',
      prompt: '给出 6 个客户的差异化需求，请候选人识别共性机会、产品边界和优先级。',
      requiredEvidence: '分类依据、被放弃的信息、边界判断、验证假设。',
      anchors: {
        1: '逐条整理需求，主要按客户级别或紧急程度排序。',
        3: '能识别共性场景，说明边界和取舍，并提出验证计划。',
        5: '能建立可复用框架，识别隐含机制，并兼顾短期验证与长期演进。',
      },
    },
    {
      id: 'A-02',
      dimension: '产品闭环与结果',
      weight: 25,
      mapsTo: ['O-02', 'C-02'],
      method: '项目复盘面试',
      owner: '高级产品经理',
      prompt: '选择一个由你主导、从机会判断推进到上线验证的产品案例。',
      requiredEvidence: '本人角色、关键取舍、MVP 范围、采用结果、复盘动作。',
      anchors: {
        1: '重点描述过程和上线，无法说明结果或本人贡献。',
        3: '完整呈现判断、推动、验证和基于结果的迭代。',
        5: '不仅完成闭环，还建立可复用机制并产生可量化规模效应。',
      },
    },
    {
      id: 'A-03',
      dimension: '跨团队决策推动',
      weight: 20,
      mapsTo: ['O-01', 'O-02', 'C-03'],
      method: '行为面试 + 交叉面',
      owner: '研发负责人',
      prompt: '讲述一次销售承诺、交付需求和产品方向发生冲突时，你如何推动决策。',
      requiredEvidence: '冲突各方目标、决策依据、关键影响动作、承诺和最终结果。',
      anchors: {
        1: '等待上级决策，或将沟通次数作为推动结果。',
        3: '能形成决策依据，推动关键角色明确取舍并完成闭环。',
        5: '改变组织协作机制，使后续同类冲突能够更高效解决。',
      },
    },
    {
      id: 'A-04',
      dimension: '指标意识与价值验证',
      weight: 15,
      mapsTo: ['O-03', 'C-04'],
      method: '案例任务',
      owner: '产品负责人 / 数据伙伴',
      prompt: '为一个标准化能力设计验证指标，并说明数据不完整时如何判断是否继续投入。',
      requiredEvidence: '结果指标、过程指标、基线、数据限制、停止或扩大条件。',
      anchors: {
        1: '以功能上线或需求完成作为唯一成功标准。',
        3: '能定义采用与业务结果指标，并说明基线和决策方式。',
        5: '能处理归因和数据限制，用多类证据支持投资决策。',
      },
    },
    {
      id: 'A-05',
      dimension: '动机与阶段适配',
      weight: 10,
      mapsTo: ['O-01', 'O-03'],
      method: '用人经理面试',
      owner: '用人经理',
      prompt: '为什么愿意进入一个边界尚未完全确定、需要从项目中重建产品秩序的岗位？',
      requiredEvidence: '真实动机、对模糊性的理解、希望建立的机制、风险预期。',
      anchors: {
        1: '期待职责和资源已经清晰，不愿处理组织冲突。',
        3: '理解阶段挑战，并有相似环境下自我驱动的证据。',
        5: '能预判关键风险，提出可信的进入策略并体现长期建设意愿。',
      },
    },
  ],
  constraints: [
    { label: '编制', value: '新增正式编制 1 人', state: '已确认' },
    { label: '职级', value: '3-2 至 4-1', state: 'HR 已确认' },
    { label: '地点', value: '北京 / 上海', state: '已确认' },
    { label: '期望到岗', value: '8 周内', state: '存在供给风险' },
    { label: '硬门槛', value: '不将同行业年限作为硬筛', state: '待经理确认' },
  ],
};

export const recruitingPortrait = {
  basicInfo: [
    { label: '所属团队', value: '企业服务产品部' },
    { label: '招聘类型', value: '新增编制 · 1 人' },
    { label: '职级', value: '3-2 至 4-1' },
    { label: '汇报对象', value: '产品负责人' },
    { label: '工作地点', value: '北京 / 上海' },
    { label: '期望到岗', value: '8 周内' },
    { label: '薪酬范围', value: '按权限可见', restricted: true },
    { label: 'HC 状态', value: '已审批', confirmed: true },
  ],
  approvedContext: {
    reason: '企业服务业务正从单客户定制交付转向标准产品经营，需要建立跨项目的产品化责任主体。',
    coreProblem: '相似客户需求重复建设，缺少统一的产品边界、标准化路线和规模复用机制。',
    evidence: ['E-01', 'E-02', 'E-04'],
  },
  candidateDefinition: '寻找一名能够从多个复杂客户项目中抽象共性需求、形成标准产品路线，并主导产品完成多客户验证的 B 端产品经理。',
  sourcingBrief: {
    targetTypes: [
      {
        code: 'A',
        title: '企业 SaaS / 平台产品经理',
        why: '通常同时具备多客户、标准产品和持续经营经验。',
        check: '是否把多个客户需求沉淀成统一能力，并产生复用结果。',
      },
      {
        code: 'B',
        title: '从交付转产品的产品负责人',
        why: '熟悉复杂客户问题，也经历过从项目制走向产品化。',
        check: '是否真正摆脱单客户视角，而不是更高级的项目交付。',
      },
      {
        code: 'C',
        title: '行业解决方案产品经理',
        why: '业务理解深，能够处理客户差异和多角色协同。',
        check: '是否主导过标准产品，而不只是输出方案和完成验收。',
      },
    ],
    titles: ['企业产品经理', 'B 端产品经理', '平台产品经理', '行业产品经理', '解决方案产品经理'],
    keywords: ['多客户', '标准化', '产品化', '平台能力', 'MVP', '客户试点', '采用率', '复用率'],
    query: '(企业产品经理 OR 平台产品经理 OR B端产品经理) AND (标准化 OR 产品化 OR 平台化) AND (多客户 OR 复用 OR 客户试点)',
    nonTarget: ['只有单客户定制项目', '主要负责需求承接和项目验收', '只描述协调研发与推动上线', '只有同行经验，没有产品化结果'],
  },
  resumeScreening: {
    decision: 'P-01 与 P-02 都明确：建议推进；命中一项：电话验证；两项都不明确：暂不推进。',
    coreSignals: [
      {
        id: 'P-01',
        title: '多客户需求抽象',
        required: true,
        lookFor: ['覆盖多个客户或业务单元', '形成统一模块、平台能力或产品边界', '出现复用率、交付效率等结果'],
        notEnough: '只写“负责客户需求管理”或“完成多个项目交付”不算。',
      },
      {
        id: 'P-02',
        title: '完整产品化闭环',
        required: true,
        lookFor: ['亲自参与机会判断和 MVP 定义', '推动真实客户试点', '根据采用、复用或业务结果继续迭代'],
        notEnough: '只写“推动产品上线”但没有验证结果不算。',
      },
      {
        id: 'P-03',
        title: '复杂协作与取舍',
        required: false,
        lookFor: ['处理销售承诺与产品路线冲突', '推动客户定制与标准化取舍', '本人形成依据并促成决策'],
        notEnough: '只写“协调各方、保障项目进度”不能证明决策能力。',
      },
    ],
    rules: [
      { label: '直接推进', condition: 'P-01、P-02 证据明确，且能看到本人贡献', tone: 'go' },
      { label: '电话验证', condition: '命中一项核心证据，另一项经历存在但结果模糊', tone: 'verify' },
      { label: '暂不推进', condition: '只有项目交付、需求承接或同行业标签', tone: 'stop' },
    ],
  },
  phoneScreen: [
    {
      question: '讲一个你把多个客户需求变成标准产品能力的案例。',
      listenFor: '客户差异、抽象过程、产品边界和最终复用结果。',
      risk: '只是汇总需求，没有说明如何取舍。',
    },
    {
      question: '哪些客户需求最后没有做？为什么？',
      listenFor: '明确的判断依据、影响对象和本人决策。',
      risk: '全部归因于领导决定，无法说明个人判断。',
    },
    {
      question: '产品上线后如何判断值得继续投入？',
      listenFor: '采用率、复用率、交付效率或明确业务结果。',
      risk: '把按时上线当作唯一成功标准。',
    },
    {
      question: '这件事里你本人推动了哪个关键决定？',
      listenFor: '本人角色、关键动作、阻力和最终结果。',
      risk: '反复使用“我们”，说不清本人贡献。',
    },
  ],
  candidateCalibration: {
    source: '人才库 · 演示候选人',
    samples: [
      {
        id: 'C-017',
        name: '候选人 A',
        currentRole: '企业平台产品经理 · 6 年',
        agentDecision: '建议推进',
        tone: 'go',
        evidence: ['多客户抽象', '产品化闭环'],
        gap: '复杂冲突案例待验证',
        managerDecision: '待确认',
      },
      {
        id: 'C-026',
        name: '候选人 B',
        currentRole: '行业解决方案产品经理 · 7 年',
        agentDecision: '电话验证',
        tone: 'verify',
        evidence: ['行业理解', '多客户经验'],
        gap: '标准产品结果不清晰',
        managerDecision: '待确认',
      },
      {
        id: 'C-031',
        name: '候选人 C',
        currentRole: '大客户交付产品经理 · 8 年',
        agentDecision: '暂不推进',
        tone: 'stop',
        evidence: ['复杂项目交付'],
        gap: '单客户定制，无复用证据',
        managerDecision: '待确认',
      },
    ],
  },
  decisiveExperiences: [
    {
      id: 'P-01',
      title: '跨客户需求抽象',
      resumeSignal: '经历覆盖多个客户或业务单元；出现共性需求、产品边界、标准化或平台化成果。',
      verify: '如何识别共性、保留差异、决定不做什么，并最终形成什么产品能力。',
      evidence: ['E-04', 'E-08'],
    },
    {
      id: 'P-02',
      title: '产品化完整闭环',
      resumeSignal: '主导过从机会判断、MVP、核心客户试点到采用、复用或规模推广的完整过程。',
      verify: '本人角色、关键取舍、验证指标、真实结果以及根据结果作出的迭代。',
      evidence: ['E-05'],
    },
    {
      id: 'P-03',
      title: '复杂决策推动',
      resumeSignal: '在销售、交付、解决方案和研发目标冲突时，推动过产品路线或范围取舍。',
      verify: '各方目标、决策依据、影响动作、关键承诺以及最终是否完成闭环。',
      evidence: ['E-02', 'E-05'],
    },
  ],
  marketMap: {
    archetypes: [
      { code: 'A', title: 'B2B SaaS / 企业平台产品经理', note: '优先验证多客户标准化和产品经营结果' },
      { code: 'B', title: '交付转标准产品的产品负责人', note: '优先验证是否真正摆脱单客户视角' },
      { code: 'C', title: '行业解决方案产品经理', note: '必须具备多客户产品化结果，而非方案交付' },
      { code: 'D', title: '复杂内部平台产品经理', note: '需验证外部客户意识和商业化适应性' },
    ],
    titles: ['企业产品经理', 'B 端产品经理', '平台产品经理', '行业产品经理', '解决方案产品经理'],
    strongSignals: ['多客户', '共性需求', '标准化', '产品化', '平台能力', '产品边界', 'MVP', '客户试点', '采用率', '复用率'],
    nonTarget: ['只有单客户项目交付', '主要负责需求承接与验收', '只描述协调研发和推动上线', '有同行经验但没有产品化结果'],
  },
  decisionBoundary: {
    must: ['跨客户抽象', '产品化闭环'],
    key: ['复杂组织推动'],
    preferred: ['企业服务', '平台产品', '同行业经验'],
    substitutes: ['同行业经验可由相似业务复杂度替代', '企业服务背景可由复杂 B 端平台经验替代'],
    exclusions: ['只有定制交付，没有标准产品结果', '无法说明本人贡献和结果证据'],
    priority: '产品化闭环证据 ＞ 复杂 B 端经验 ＞ 跨团队推动 ＞ 同行业经验',
  },
  calibration: {
    state: '待首轮市场校准',
    summary: '当前画像由业务需求和历史案例推导，尚未使用真实候选人样本验证人才池宽度。',
    next: '建议 HR 与用人经理共同查看 5 份代表性候选人，并记录“推进 / 不推进”的真实原因。',
  },
};

export const traceRows = [
  { outcome: 'O-01 90 天诊断', task: 'T-01 共性抽象', capability: 'C-01 产品化抽象', assessment: 'A-01 案例面试' },
  { outcome: 'O-02 MVP 验证', task: 'T-03 MVP 推动', capability: 'C-02 产品闭环', assessment: 'A-02 项目复盘' },
  { outcome: 'O-02 MVP 验证', task: 'T-02 优先级决策', capability: 'C-03 跨团队推动', assessment: 'A-03 行为面试' },
  { outcome: 'O-03 规模复用', task: 'T-05 指标经营', capability: 'C-04 价值验证', assessment: 'A-04 案例任务' },
];

export const versions = [
  { id: 'v04', name: '草稿 v0.4', meta: '补全成功结果与人才证据', time: '刚刚', active: true },
  { id: 'v03', name: '草稿 v0.3', meta: '确认 90 天优先结果', time: '10:38' },
  { id: 'v02', name: '草稿 v0.2', meta: '确认业务问题与岗位变化', time: '10:34' },
  { id: 'v01', name: '草稿 v0.1', meta: '创建澄清会话', time: '10:29' },
];
